model_name: "ConvE"
datasets:
  - dataset: "umls"
    parameters:
      learning_rate: 0.00104073544
      hidden_size: 100
      hidden_size_1: 20
      input_dropout: 0.2
      feature_map_dropout: 0.2
      hidden_dropout: 0.4
      label_smoothing: 0.2
      batch_size: 16
      optimizer: "rms"
      neg_rate: 0
      epochs: 500
      neg_rate: 0