model_name: "TransE"
datasets:
  - dataset: "PhenoSimple"
    parameters:
      learning_rate: 0.003512853763729802
      l1_flag: True
      hidden_size: 299
      batch_size: 89
      epochs: 500
      margin: 9.884319967513747
      optimizer: "rms"
      sampling: "uniform"
      neg_rate: 1